name: Build UABEA Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Remove TexToolWrap VC++ project
      run: dotnet sln UABEAvalonia.sln remove TexToolWrap/TexToolWrap.vcxproj

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet publish /p:NativeLib=Shared --runtime linux-x64 --configuration release --self-contained false
    
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: uabea-ubuntu
        path: UABEAvalonia/bin/Release/net8.0